// Generated by CoffeeScript 1.6.2
var WIAfterUpdate;

smite(eval(s));

Unionize.connect = connect;

WIAfterUpdate = WI.after.update(function(userId, doc, fieldNames, modifier, options) {});

this.feedItems = React.createClass({
  "getInitialState": function() {
    return {
      feeds: WI.findOne({
        "_id": user
      })
    };
  },
  "componentDidMount": function() {
    var self;

    self = this;
    return Tracker.autorun(function() {
      var feed;

      feed = WI.findOne({
        "_id": user
      });
      return self.setState({
        "feeds": feed
      });
    });
  },
  "render": function() {
    var feedsList, sending;

    feedsList = [];
    if (this.state.feeds && this.state.feeds.sending) {
      sending = this.state.feeds.sending;
      feedsList = sending.map(function(feed) {
        return React.DOM.div(null, {}, feed.from + feed.to);
      });
    }
    return React.DOM.div(null, feedsList);
  }
});
