// Generated by CoffeeScript 1.6.2
var arrowofhrt, i, _i, _len, _ref;

this.s = 'L()';

this.user = 'wiber';

this.WIFound = function(id) {
  var found;

  smite(id, 'scouting nemo', eval(s));
  found = WI.find({
    _id: id
  }, {
    limit: 1
  }).count();
  smite(id, found, 'finding nemo', eval(s));
  return found;
};

this.WFound = function(id) {
  var found;

  smite(id, 'scouting nemo', eval(s));
  found = W.find({
    _id: id
  }, {
    limit: 1
  }).count();
  smite(id, found, 'finding nemo', eval(s));
  return foun;
};

this.smite = (function() {
  var context;

  context = 's';
  return Function.prototype.bind.call(console.log, console, context);
})();

console.warn = function() {};

arrowofhrt = false;

this.daff = function() {
  var d;

  if (Meteor.isServer && arrowofhrt) {
    this.time = process.hrtime();
    d = process.hrtime(time);
    d = d[1] + d[0] * 1e9;
    return d;
  } else {
    return new Date().getTime();
  }
};

this.dif = [];

this.consoling = true;

this.t = function() {
  var d;

  dif.push(daff());
  if (!(Meteor.isServer && consoling)) {
    console.timeEnd('elapsed');
    console.time('elapsed');
  }
  console.log(d = dif.slice(-1)[0] - dif[0]);
  return d;
};

Meteor.methods({
  "t": function() {
    return L();
  }
});

this.L = function() {
  var caller_line, clean, end, err, getErrorObject, index, pathChars, r, start;

  t();
  if (Meteor.isClient) {
    return '';
  } else {
    getErrorObject = function() {
      var err;

      try {
        throw Error('');
      } catch (_error) {
        err = _error;
        return err;
      }
    };
    err = getErrorObject();
    caller_line = err.stack.split('\n')[4];
    index = caller_line.indexOf('at ');
    clean = caller_line.slice(index + 2, caller_line.length);
    pathChars = 38;
    start = clean.length - pathChars;
    end = start + 32;
    r = clean.slice(start, +end + 1 || 9e9) + ' ' + t();
    return r;
  }
};

this.smiter = (function() {
  var context;

  context = eval(s);
  return Function.prototype.bind.call(console.log, console, context);
})();

_ref = '123';
for (_i = 0, _len = _ref.length; _i < _len; _i++) {
  i = _ref[_i];
  smite(eval(s), dif, dif[0] - dif.slice(-1)[0], i, 'counting to three t()');
  if (Meteor.isServer) {
    new smiter(i);
  }
}

this.W = new Meteor.Collection('W');

this.WI = new Meteor.Collection('WI');

this.Unionize.W = W;

this.Unionize.WI = WI;

eval('smiter("lives")');

smite('smiter live!', eval(s));
