// Generated by CoffeeScript 1.6.2
Tinytest.add('reactjs - 5 dom element equals to data', function(test, next) {
  var intervalId, testingRecommend;

  testingRecommend = {
    from: 'another1',
    to: 'wiber6'
  };
  connect(testingRecommend);
  intervalId = null;
  return intervalId = setInterval(function() {
    var domString;

    domString = React.renderComponentToString(feedItems(null));
    if (domString.match(testingRecommend.from + testingRecommend.to)) {
      test.equal(true, true);
      next();
      return clearInterval(intervalId);
    }
  }, 500);
});
