// Generated by CoffeeScript 1.6.2
var recommendation;

if (Meteor.isClient) {
  this.recFrom = 'picture';
  recommendation = {
    to: user,
    from: recFrom
  };
  Tinytest.addAsync('update - from client outbox to client inbox', function(test, next) {
    var inbox;

    connect(recommendation);
    inbox = Tracker.autorun(function(computation) {
      if (!!W.findOne({
        to: user
      })) {
        test.equal(recFrom, W.findOne({
          to: user
        }).from);
        next();
        return;
      }
    });
  });
}
